# This is a basic workflow that is manually triggered

name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/checkout@v2
      name: Checkout
      with:
        persist-credentials: false

    - name: install
      run: npm i

    - name: build
      run: npm run build

    - name: deploy
      run: npm run deploy
